[fast-reboot][cosmetic] Fixed debug/error prints with the correct reboot type (#4285)
- What I did
Updated reboot type in debug/error prints

- How I did it
By using REBOOT_SCRIPT_NAME var instead of a hard-coded warm-reboot

- How to verify it
Run warm-reboot -v and fast-reboot -v and check the logs

Signed-off-by: Yair Raviv <yraviv@nvidia.com>

diff --git a/scripts/fast-reboot b/scripts/fast-reboot
--- a/scripts/fast-reboot
+++ b/scripts/fast-reboot
@@ -68,7 +68,7 @@ function error()
         message="asic$DEV: $message"
     fi
     echo "$message" >&2
-    logger -p user.err "Error seen during warm-reboot shutdown process: $message"
+    logger -p user.err "Error seen during $REBOOT_SCRIPT_NAME shutdown process: $message"
 }
 
 function debug()
@@ -339,7 +339,7 @@ function filter_asic_list()
 function clear_boot()
 {
     # common_clear
-    debug "${REBOOT_TYPE} failure ($?) cleanup ..."
+    debug "${REBOOT_SCRIPT_NAME} failure ($?) cleanup ..."
 
     /sbin/kexec -u -a || /bin/true
 
@@ -737,9 +737,9 @@ function check_pfc_storm_active()
     fi
 
     if pfcwd show stats $options --check-storm >/dev/null 2>&1; then
-        debug "No active PFC storms detected. Safe to proceed with warm-reboot..."
+        debug "No active PFC storms detected. Safe to proceed with $REBOOT_SCRIPT_NAME..."
     else
-        error "PFC storm detected. Aborting warm-reboot to prevent failure in recovery path..."
+        error "PFC storm detected. Aborting $REBOOT_SCRIPT_NAME to prevent failure in recovery path..."
         exit ${EXIT_PFC_STORM_DETECTED}
     fi
 }
